# Generated by Django 4.1.4 on 2022-12-26 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autho',
            new_name='author',
        ),
    ]
