# Generated by Django 4.1.4 on 2022-12-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogg', '0003_post_title_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title_tag',
            field=models.CharField(max_length=200),
        ),
    ]
